### ISSUE TITLE
Problem with grave fog and losing progress on death

### ISSUE THREAD

**Issue by Lamyoya** [Corail31/tombstone_lite#86] opened 2022-09-20 11:25 UTC
### Minecraft Version

1.16.5

### Forge Version

36.2.39

### Corail Tombstone Version

6.8.0

### What happened?

Hello, I am playing on 1.16.5, having problem with 2 aspects of the mod. Firstly, decorative graves seem to never produce fog, tried setting in the config and even if I set them to always produce it, they never do. The bug isn't only visual, souls also don't appear on decorative graves(waited for 5 game days). Secondly, every time I die, I lose all the progress in knowledge of death and alignment (no config files are set to do that, checked everything). I've seen this problem in several posts on the mod page, though nobody seems to have found the solution or the cause of this happening. Tested for these with just Corail Tombstone, the issue with losing progress disappeared while the fog still doesn't appear.

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone (required)

Yes

### Occurence

occurs all the time

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment] 2022-09-20 13:21
The template asks you to test with only Corail Tombstone.
You found that your problem of knowledge kept on death is not happening with only Corail Tombstone: so you have to locate the problem in your others mods. What do you want me to do if you don't other than close the issue ?
Checks your log if you don't have a message related to "a mod canceling the death event".
"I've seen this problem in several posts on the mod page, though nobody seems to have found the solution or the cause of this happening" -> with Magma and **the template is explicit about Magma & Mohist**.
Issues should be in separate topics: about the fog particles, the fog doesn't render in 6.8.0 due to an inversed condition (an easy solution is to set the fog fensity to 0) and the fix was added to 6.8.1 (6.7.9, the recommanded version hasn't this problem).
About the grave soul, the config "chance_soul" is a chance on 1000 (by default it's 100 so, 10% chance), i changed the minimum value for the config "time_soul" in 6.8.1 so you can make test.
NB: Feel free to edit your issue about the initial problem with the incompatible mod for the "knowledge kept on death" if you want more help.

**Closed as completed by Corail31** 2022-09-20 13:21 UTC
Labels: 1.16.5, tested to work properly
